In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

### 2 dimension array

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### access elements by bracket

In [24]:
a=np.arange(3, 60, 3)
a

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57])

In [35]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [36]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### concatination

In [43]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))


x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### ndarray.ndim, ndarray.size, ndarrray.shape

In [190]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim
# array_example.size
# array_example.shape

3

In [195]:
t = np.array([[5,6,7],
               [8,9,10],
               [12,14,2]])
t

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [12, 14,  2]])

In [198]:
t.ndim
t.size
t.shape

(3, 3)

In [203]:
t = np.arange(9)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [204]:
t = t.reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [206]:
np.reshape(t, newshape=(1, 9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [207]:
a = np.array([1,2,3,4,5,6,7,8,8])
a.shape

(9,)

In [208]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 8]])

In [209]:
b.shape

(1, 9)

In [210]:
b = a[:, np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [8]])

### reshaping

In [50]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)
np.reshape(a, newshape=(1, 6), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


### newaxis and expand

In [60]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
(6,)

a2 = a[np.newaxis, :]
a2.shape
(1, 6)

row_vector = a[np.newaxis, :]
row_vector.shape
(1, 6)

col_vector = a[:, np.newaxis]
col_vector.shape
(6, 1)

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

b = np.expand_dims(a, axis=1)
b.shape

c = np.expand_dims(a, axis=0)
c.shape
(1, 6)

(1, 6)

In [66]:
data = np.array([1, 2, 3])

data[1]

data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [68]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
print(a[a < 5])

five_up = (a >= 5)
print(a[five_up])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]


In [71]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [72]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [73]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [75]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
b = np.nonzero(a < 5)
print(b)

list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [79]:
print(a[b])

[1 2 3 4]


### Existing data

In [92]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

arr1 = a[3:8]
arr1

a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))

np.hstack((a1, a2))

# split an arrary
x = np.arange(1, 25).reshape(2, 12)
x

np.hsplit(x, (3, 4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [94]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
b1 = a[0, :]
b1

b1[0] = 99
b1

array([99,  2,  3,  4])

In [99]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [105]:
b = np.array([[1, 1], [2, 2]])
b

array([3, 3])

In [106]:
b.sum(axis=0)

array([3, 3])

In [104]:
b.sum(axis=1)

array([2, 4])

In [107]:
# multiplication with a digit
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [111]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data
data[0, 1]
data[0:2, 0]

array([1, 3])

In [115]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

ones_row = np.array([[1, 1]])
ones_row

data + ones_row


array([[2, 3],
       [4, 5],
       [6, 7]])

In [116]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [117]:
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [120]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

In [125]:
import numpy as np 
a = np.array([1,2,3,4,5])
a

b = np.zeros(2)
b

c= np.ones(3)
c

d = np.empty(6)
d

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313, 2.54639495e-313])

# practics session

In [127]:
import numpy as np
food = np.array(["pakora","Samosa","Raita"])
food

array(['pakora', 'Samosa', 'Raita'], dtype='<U6')

In [133]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [134]:
type(price)

numpy.ndarray

In [135]:
type(food)

numpy.ndarray

In [137]:
len(price)
len(food)

3

In [139]:
price[0:]

array([5, 5, 5])

In [141]:
food[1]

'Samosa'

In [142]:
price.mean()

5.0

In [143]:
# zero method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [144]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [145]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [146]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [148]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [149]:
# table
np.arange(0,50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [150]:
# line space
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [151]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [152]:
np.ones(8, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1.])

# array functions

In [172]:
ab=np.array([10,12,15,2,4,5,100,320,0.5,10])
c=ab.sort()
bc = np.array ([12,3,23,12.4,11])
d =np.concatenate((ab,bc))
d.sort()
d

array([  0.5,   2. ,   3. ,   4. ,   5. ,  10. ,  10. ,  11. ,  12. ,
        12. ,  12.4,  15. ,  23. , 100. , 320. ])

# 2-D arrays

In [187]:
a = np.array([[1,2],[5,6]])
a

array([[1, 2],
       [5, 6]])

In [185]:
j = np.array([[12,22],[34,43]])
j

array([[12, 22],
       [34, 43]])

In [188]:
np.concatenate((a,j),axis=0)

array([[ 1,  2],
       [ 5,  6],
       [12, 22],
       [34, 43]])

In [189]:
np.concatenate((a,j),axis=1)

array([[ 1,  2, 12, 22],
       [ 5,  6, 34, 43]])